### PR TITLE
define semigroup instances

### PR DESCRIPTION
**Pull request by strake**

### CODE REVIEW

**Comment by AlexeyRaga** [comment]
@strake thanks a lot!
Could you please enable CircleCI on your fork? It is very helpful to be able to see that the build is green when merging...

**Comment by strake** [comment]
@AlexeyRaga how can i do so?

**Comment by AlexeyRaga** [comment]
@strake I am looking at CIrcleCI configuration and there is an option "Build forked pull requests". It was off by default, and I switched it on. If you push to your branch again then, I hope, it will start building without you configuring CI on your fork. Please push something (even if it just amending the commit message) and we'll see! :)

But in general, to use CircleCI you need to go to https://circleci.com/, click `Log In` -> `Log in with GitHub` and click `Add projects` there. Then it will trigger the build every time you push.

**Comment by strake** [comment]
Checks passed, PTAL

**Comment by AlexeyRaga** [comment]
@strake thanks a lot for the help!

**Pull request merged**
