### PR TITLE
Properly handle namespaces according to Avro spec.

### PR DESCRIPTION
**Pull request by TikhonJelvis**
# Namespace Handling

This PR ensures that we properly infer and handle namespaces in Avro specs. In code, this is reflected by adding a `namespace` field to `TypeName` and taking the namespace field *out* of `Record`, `Enum` and `Fixed`:

```
data TypeName = TN { baseName  :: T.Text
                   , namespace :: [T.Text]
                   }
```

This ensures that we *always* consider namespaces when comparing Avro type names, using them as keys... etc. The idea is that we take care of inferring and normalizing namespaces in parsing so that 'TypeName' values are 100% canonical in the rest of the code—we can consistently compare them for equality regardless of how they were specified in the Avro schema itself.

As a bonus, this let us simplify a few awkward edgecases in the code that tried to deal with namespace logic. Every part of the code outside of parsing now uses `TypeName`s as opaque values without caring about names vs namespaces.

The actual namespace inference logic is handled in the `FromJSON` instance for `Schema` and follows the rules laid out in the Avro specification. Given a definition of a named type (Record, Enum or Fixed) with a given `"name"` and `"namespace"` field, the fullname is defined as follows:

  1. If the `"name"` field contains dots, it is parsed as a *fullname* and the `"namespace"` field is ignored if present. The name field `"com.example.Foo"` would be parsed as a type name with the name `"Foo"` and the namespace `"com.example"`.

  2. Otherwise, if both the `"name"` and `"namespace"` fields are set, they make up the *fullname*.

  3. If only the `"name"` field is specified, the `"namespace"` is inferred from the namespace of the *most tightly enclosing schema*, if any. If there is no enclosing schema, the namespace is null. (In `TypeName`, this corresponds to a namespace of `[]`.)

The namespace logic for references to named types follows steps 1 and 3.

# Fixes

This fixes all the problems I brought up in #19:

  * there is no distinction between `Nothing` and `Just ""`—both become `[]` in the new scheme
  * `TypeName` now contains both the name and the namespace, forcing us to handle namespaces consistently throughout the codebase
  * namespaces are inferred following the rules laid out in the Avro specification (which weren't as ugly as I though)

# Template Haskell

This PR also updates the Template Haskell code to handle namespaces correctly. A type like `com.example.Foo` becomes the Haskell type `Com'example'Foo`.

However, this breaks compatibility with the old Template Haskell code and leads to *very* verbose names if your schemas use non-trivial namespaces. To maintain backwards compatibility and let people have nicer generated type names, the Template Haskell code can be configured to ignore namespaces. Now there are four functions to derive Avro types:

  * `deriveAvro` which ignores namespaces and derives to/from Avro instances
  * `deriveAvroWithNamespaces` which handles namespaces and derives to/from Avro instances
  * `deriveFromAvro` which ignores namespaces and derives only from Avro instances
  * `deriveFromAvroWithNamespaces` which handles namespaces and derives only from Avro instances

### CODE REVIEW

**Comment by TikhonJelvis** [comment]
I updated a couple of the Template Haskell tests to handle namespaces, but this PR still needs dedicated tests for the new logic.

I'll add those tests soon as well as resolving conflicts with `master`. Meanwhile, I'd love feedback on the code and how I handle namespaces. It's definitely a bit awkward, but I think it's mostly Avro's fault in this case!

**Comment by TikhonJelvis** [comment]
Got the branch merged with all the recent changes to `master`.

The main difference is that `NamespaceBehavior` got folded into `DeriveOptions`. Instead of a `deriveAvroWithNamespaces` function, you now have an even *more* verbose incantation:

```
deriveAvroWithOptions (defaultDeriveOptions { namespaceBehavior = HandleNamespaces }) "test/data/reused.avsc"
```

Thanks to the TH staging restriction, you can't even extract the options into a variable in the same module (as far as I can tell).

Now that all the tests pass, I'm pretty sure I merged all the new logic in correctly. This involved a fiddly conflict resolution, so the merge commit is pretty large.

I should still write some tests to check the namespace handling logic specifically, but in the meantime the `THUnionSpec` test seems to have stressed it pretty well, and I updated a couple of the other TH tests to derive namespace-aware Haskell types. At least the basic namespace handling logic is tested and solid.

I'll write some test cases to handle the various edgecases, but I don't feel like doing it tonight :P.

**Comment by TikhonJelvis** [comment]
One thing to note: this change means that the JSON definition of Avro schemas is not exactly preserved in a fromJSON → toJSON round-trip. All names in Avro schemas are normalized to fully-qualified strings. The *semantics* of the schema remain the same, but the exact JSON changes.

For example, the following schema:

```
{
  "type" : "record",
  "name" : "Foo",
  "namespace" : "com.example",
  "fields" : [
    {
      "name" : "bar",
      "type" : {
        "type" : "record",
        "name" : "Bar",
        "fields" : [
          {
            "name" : "baz",
            "type" : "int"
          }
        ]
      }
    }
  ]
}
```

turns into:

```
{
  "aliases": [],
  "name": "com.example.Foo",
  "type": "record",
  "order": "ascending",
  "fields": [
    {
      "aliases": [],
      "name": "bar",
      "type": {
        "aliases": [],
        "name": "com.example.Bar",
        "type": "record",
        "order": "ascending",
        "fields": [
          {
            "aliases": [],
            "name": "baz",
            "type": "int",
            "order": "ascending"
          }
        ]
      },
      "order": "ascending"
    }
  ]
}
```

We already don't promise exact round-tripping (things like the `"order"` field), but this is still a change in the JSON behavior of the `Schema` type.

**Comment by AlexeyRaga** [comment]
Thanks!
I will have a look closer soon. 

In your latest example with JSON, do you think it is possible to still infer the original schema? As far as I can remember Avro spec states that in `com.example.data` we can assume that `com.example` is a namespace and `data` is a name. So we could theoretically split the full name by `.` and then not repeat namespace on children?

And maybe same can be done for template generation (can't wait for `DeriveVia`)? We only need to generate long names if these names clash somehow...

**Comment by TikhonJelvis** [comment]
Now that you mention it, the logic for leaving out the namespace when it would be inferred would be easy to implement.

Changing the Template Haskell to only use namespaces when needed to disambiguate is trickier. It would require extra bookkeeping in an already fiddly part of the code and it would cause the TH-generated names to change in unpredictable ways. If you relied on that TH behavior and all of a sudden the schema got some ambiguous name, the TH types would change even if you never use the ambiguous name yourself.

**Comment by AlexeyRaga** [comment]
Yeah, TH could be a bit more difficult. Although there is `lookupTypeName :: String -> Q (Maybe Name)` which we can use to determine whether a name has already been registered (and therefore is conflicting) or not.

**Comment by AlexeyRaga** [comment]
Looks good to me.
It would be great to add namespaces inference for schemas, but I guess we can iterate on it.

**Comment by dwincort** [comment]
Hi there,

I'm not sure the merge went through exactly right.  It used to be that it could handle unions of up to 5 elements, but post-merge, it tops out at 2:
https://github.com/GaloisInc/avro/pull/52/files#diff-8c2e874235b83f3085b8143a099cdedcL429

**Comment by TikhonJelvis** [comment]
I definitely didn't mean to affect the union handling in TH at all.

This PR needs a bit more review and testing before it's ready. I can create another PR fixing things up or we could try reverting the merge and then extending this PR (which would take a bit of git magic). @AlexeyRaga?

**Comment by TikhonJelvis** [comment]
After thinking about it, I decided it would be easier to just submit a few small PRs fixing issues with this PR, starting with replacing the logic for larger unions.

**Comment by AlexeyRaga** [comment]
I agree, small  PRs are better

**Pull request merged**
