### PR TITLE
Fixed how we handle unions of records with the same fields.

### PR DESCRIPTION
**Pull request by TikhonJelvis**
When deserializing an Avro object, we need to select records based on their names, not just their fields. This lets us have unions with two records that have different names but the same set of fields (which is totally valid in Avro).

In principle, we can select named types based *only* on names, not looking at the fields at all. Avro requires full names in schemas to be unique. However, I did not make this change here to avoid changing the existing behavior of the library too much.

### CODE REVIEW

**Comment by TikhonJelvis** [comment]
@AlexeyRaga As part of writing some tests for the JSON parsing/serializing logic, I found out that unions aren't handled correctly when the branches are different records with the same fields.

I added a general test cases for unions that includes an example like this and fixed the issue by changing the `Eq` instance for `Schema`.

**Comment by TikhonJelvis** [comment]
In general, Avro requires "full names" of types (ie namespace + name) to be unique in the schema. I think it would make sense to change how we handle equality for all named types to *only* look at the name, but wanted to keep this PR scoped to *just* this fix.

**Comment by AlexeyRaga** [comment]
Thanks!

**Comment by TikhonJelvis** [comment]
Probably worth noting that this change is technically backwards-incompatible, but the incompatibility should only manifest on schemas that were handled incorrectly previously.

**Pull request merged**
